"""create initial schema

Revision ID: 1c92569d774c
Revises: 
Create Date: 2026-05-28 11:47:19.002511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c92569d774c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('delivery_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('max_orders', sa.Integer(), nullable=False),
    sa.Column('current_order_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_windows_active'), 'delivery_windows', ['active'], unique=False)
    op.create_index(op.f('ix_delivery_windows_delivery_date'), 'delivery_windows', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_windows_id'), 'delivery_windows', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_windows_name'), 'delivery_windows', ['name'], unique=False)
    op.create_index(op.f('ix_delivery_windows_region'), 'delivery_windows', ['region'], unique=False)
    op.create_table('driver_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('vehicle_type', sa.String(length=120), nullable=True),
    sa.Column('availability_notes', sa.Text(), nullable=True),
    sa.Column('territory_preference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_interests_city'), 'driver_interests', ['city'], unique=False)
    op.create_index(op.f('ix_driver_interests_email'), 'driver_interests', ['email'], unique=False)
    op.create_index(op.f('ix_driver_interests_id'), 'driver_interests', ['id'], unique=False)
    op.create_index(op.f('ix_driver_interests_state'), 'driver_interests', ['state'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('territory', sa.String(length=120), nullable=True),
    sa.Column('vehicle_type', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_territory'), 'drivers', ['territory'], unique=False)
    op.create_table('marketing_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('content_theme', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('generated_caption', sa.Text(), nullable=True),
    sa.Column('generated_hashtags', sa.Text(), nullable=True),
    sa.Column('generated_video_prompt', sa.Text(), nullable=True),
    sa.Column('generated_script', sa.Text(), nullable=True),
    sa.Column('target_platform', sa.String(length=40), nullable=False),
    sa.Column('target_audience', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_content_approved'), 'marketing_content', ['approved'], unique=False)
    op.create_index(op.f('ix_marketing_content_content_theme'), 'marketing_content', ['content_theme'], unique=False)
    op.create_index(op.f('ix_marketing_content_content_type'), 'marketing_content', ['content_type'], unique=False)
    op.create_index(op.f('ix_marketing_content_id'), 'marketing_content', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_content_scheduled_date'), 'marketing_content', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_marketing_content_status'), 'marketing_content', ['status'], unique=False)
    op.create_index(op.f('ix_marketing_content_target_audience'), 'marketing_content', ['target_audience'], unique=False)
    op.create_index(op.f('ix_marketing_content_target_platform'), 'marketing_content', ['target_platform'], unique=False)
    op.create_index(op.f('ix_marketing_content_title'), 'marketing_content', ['title'], unique=False)
    op.create_table('producer_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('delivery_capability', sa.String(length=255), nullable=True),
    sa.Column('online_ordering', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_interests_business_name'), 'producer_interests', ['business_name'], unique=False)
    op.create_index(op.f('ix_producer_interests_city'), 'producer_interests', ['city'], unique=False)
    op.create_index(op.f('ix_producer_interests_email'), 'producer_interests', ['email'], unique=False)
    op.create_index(op.f('ix_producer_interests_id'), 'producer_interests', ['id'], unique=False)
    op.create_index(op.f('ix_producer_interests_state'), 'producer_interests', ['state'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_active'), 'product_categories', ['active'], unique=False)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_region'), 'sources', ['region'], unique=False)
    op.create_index(op.f('ix_sources_source_name'), 'sources', ['source_name'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_sources_state'), 'sources', ['state'], unique=False)
    op.create_table('waitlist_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signup_type', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_page', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_signups_city'), 'waitlist_signups', ['city'], unique=False)
    op.create_index(op.f('ix_waitlist_signups_email'), 'waitlist_signups', ['email'], unique=False)
    op.create_index(op.f('ix_waitlist_signups_id'), 'waitlist_signups', ['id'], unique=False)
    op.create_index(op.f('ix_waitlist_signups_signup_type'), 'waitlist_signups', ['signup_type'], unique=False)
    op.create_index(op.f('ix_waitlist_signups_source_page'), 'waitlist_signups', ['source_page'], unique=False)
    op.create_index(op.f('ix_waitlist_signups_state'), 'waitlist_signups', ['state'], unique=False)
    op.create_table('cart_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_sessions_customer_id'), 'cart_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cart_sessions_id'), 'cart_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_cart_sessions_session_id'), 'cart_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_cart_sessions_status'), 'cart_sessions', ['status'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_id'), 'import_runs', ['id'], unique=False)
    op.create_index(op.f('ix_import_runs_source_id'), 'import_runs', ['source_id'], unique=False)
    op.create_table('marketing_content_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketing_content_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=80), nullable=False),
    sa.Column('asset_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['marketing_content_id'], ['marketing_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_content_assets_asset_type'), 'marketing_content_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_marketing_content_assets_id'), 'marketing_content_assets', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_content_assets_marketing_content_id'), 'marketing_content_assets', ['marketing_content_id'], unique=False)
    op.create_table('marketing_content_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketing_content_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posting_platform', sa.String(length=40), nullable=False),
    sa.Column('posting_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['marketing_content_id'], ['marketing_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_content_schedules_id'), 'marketing_content_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_content_schedules_marketing_content_id'), 'marketing_content_schedules', ['marketing_content_id'], unique=False)
    op.create_index(op.f('ix_marketing_content_schedules_posting_platform'), 'marketing_content_schedules', ['posting_platform'], unique=False)
    op.create_index(op.f('ix_marketing_content_schedules_posting_status'), 'marketing_content_schedules', ['posting_status'], unique=False)
    op.create_index(op.f('ix_marketing_content_schedules_scheduled_date'), 'marketing_content_schedules', ['scheduled_date'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('order_status', sa.String(length=40), nullable=False),
    sa.Column('delivery_window_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('delivery_city', sa.String(length=120), nullable=False),
    sa.Column('delivery_state', sa.String(length=40), nullable=False),
    sa.Column('delivery_zip', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('delivery_fee', sa.Float(), nullable=False),
    sa.Column('taxes', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=40), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['delivery_window_id'], ['delivery_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_delivery_window_id'), 'orders', ['delivery_window_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_route_id'), 'orders', ['route_id'], unique=False)
    op.create_index(op.f('ix_orders_stripe_checkout_session_id'), 'orders', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_orders_stripe_payment_intent_id'), 'orders', ['stripe_payment_intent_id'], unique=False)
    op.create_table('producers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('producer_name', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('online_order_url', sa.String(length=500), nullable=True),
    sa.Column('source_listing_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('producer_type', sa.String(length=120), nullable=True),
    sa.Column('delivery_available', sa.Boolean(), nullable=False),
    sa.Column('pickup_available', sa.Boolean(), nullable=False),
    sa.Column('online_ordering_confirmed', sa.Boolean(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('destination_type', sa.String(length=80), nullable=False),
    sa.Column('platform_detected', sa.String(length=120), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=80), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producers_business_name'), 'producers', ['business_name'], unique=False)
    op.create_index(op.f('ix_producers_city'), 'producers', ['city'], unique=False)
    op.create_index(op.f('ix_producers_id'), 'producers', ['id'], unique=False)
    op.create_index(op.f('ix_producers_online_order_url'), 'producers', ['online_order_url'], unique=False)
    op.create_index(op.f('ix_producers_producer_name'), 'producers', ['producer_name'], unique=False)
    op.create_index(op.f('ix_producers_qualified'), 'producers', ['qualified'], unique=False)
    op.create_index(op.f('ix_producers_source_id'), 'producers', ['source_id'], unique=False)
    op.create_index(op.f('ix_producers_source_listing_url'), 'producers', ['source_listing_url'], unique=False)
    op.create_index(op.f('ix_producers_state'), 'producers', ['state'], unique=False)
    op.create_index(op.f('ix_producers_website_url'), 'producers', ['website_url'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=False),
    sa.Column('delivery_window_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('route_status', sa.String(length=40), nullable=False),
    sa.Column('estimated_start_time', sa.String(length=20), nullable=True),
    sa.Column('estimated_end_time', sa.String(length=20), nullable=True),
    sa.Column('estimated_stop_count', sa.Integer(), nullable=False),
    sa.Column('estimated_order_count', sa.Integer(), nullable=False),
    sa.Column('route_pay', sa.Float(), nullable=False),
    sa.Column('route_bonus', sa.Float(), nullable=False),
    sa.Column('reassignment_priority', sa.Boolean(), nullable=False),
    sa.Column('assignment_notes', sa.Text(), nullable=True),
    sa.Column('route_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_window_id'], ['delivery_windows.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_delivery_window_id'), 'routes', ['delivery_window_id'], unique=False)
    op.create_index(op.f('ix_routes_driver_id'), 'routes', ['driver_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_reassignment_priority'), 'routes', ['reassignment_priority'], unique=False)
    op.create_index(op.f('ix_routes_region'), 'routes', ['region'], unique=False)
    op.create_index(op.f('ix_routes_route_name'), 'routes', ['route_name'], unique=False)
    op.create_index(op.f('ix_routes_route_status'), 'routes', ['route_status'], unique=False)
    op.create_table('driver_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('base_route_pay', sa.Float(), nullable=False),
    sa.Column('bonus_pay', sa.Float(), nullable=False),
    sa.Column('tip_amount', sa.Float(), nullable=False),
    sa.Column('total_pay', sa.Float(), nullable=False),
    sa.Column('payout_status', sa.String(length=40), nullable=False),
    sa.Column('payout_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_payouts_driver_id'), 'driver_payouts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_payouts_id'), 'driver_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_driver_payouts_payout_status'), 'driver_payouts', ['payout_status'], unique=False)
    op.create_index(op.f('ix_driver_payouts_route_id'), 'driver_payouts', ['route_id'], unique=True)
    op.create_table('import_error_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_error_rows_id'), 'import_error_rows', ['id'], unique=False)
    op.create_index(op.f('ix_import_error_rows_import_run_id'), 'import_error_rows', ['import_run_id'], unique=False)
    op.create_table('producer_outreach_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('import_run_id', sa.Integer(), nullable=True),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('producer_name', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('producer_type', sa.String(length=120), nullable=True),
    sa.Column('ubi', sa.String(length=80), nullable=True),
    sa.Column('registered_agent', sa.String(length=255), nullable=True),
    sa.Column('principal_office_address', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=80), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('outreach_status', sa.String(length=40), nullable=False),
    sa.Column('research_status', sa.String(length=40), nullable=False),
    sa.Column('search_url', sa.String(length=1000), nullable=True),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_outreach_candidates_city'), 'producer_outreach_candidates', ['city'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_id'), 'producer_outreach_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_import_run_id'), 'producer_outreach_candidates', ['import_run_id'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_outreach_status'), 'producer_outreach_candidates', ['outreach_status'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_priority_rank'), 'producer_outreach_candidates', ['priority_rank'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_priority_score'), 'producer_outreach_candidates', ['priority_score'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_producer_id'), 'producer_outreach_candidates', ['producer_id'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_producer_name'), 'producer_outreach_candidates', ['producer_name'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_region'), 'producer_outreach_candidates', ['region'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_research_status'), 'producer_outreach_candidates', ['research_status'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_source_id'), 'producer_outreach_candidates', ['source_id'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_state'), 'producer_outreach_candidates', ['state'], unique=False)
    op.create_index(op.f('ix_producer_outreach_candidates_ubi'), 'producer_outreach_candidates', ['ubi'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seasonal', sa.Boolean(), nullable=False),
    sa.Column('delivery_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_active'), 'products', ['active'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_featured'), 'products', ['featured'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_producer_id'), 'products', ['producer_id'], unique=False)
    op.create_index(op.f('ix_products_seasonal'), 'products', ['seasonal'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_status', sa.String(length=40), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('driver_notes', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('proof_of_delivery_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.create_index(op.f('ix_route_stops_order_id'), 'route_stops', ['order_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_stops_stop_status'), 'route_stops', ['stop_status'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cart_session_id'], ['cart_sessions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_session_id'), 'cart_items', ['cart_session_id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('product_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('delivery_window_id', sa.Integer(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_window_id'], ['delivery_windows.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_availability_available_from'), 'product_availability', ['available_from'], unique=False)
    op.create_index(op.f('ix_product_availability_available_until'), 'product_availability', ['available_until'], unique=False)
    op.create_index(op.f('ix_product_availability_delivery_window_id'), 'product_availability', ['delivery_window_id'], unique=False)
    op.create_index(op.f('ix_product_availability_id'), 'product_availability', ['id'], unique=False)
    op.create_index(op.f('ix_product_availability_product_id'), 'product_availability', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_availability_status'), 'product_availability', ['status'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_availability_status'), table_name='product_availability')
    op.drop_index(op.f('ix_product_availability_product_id'), table_name='product_availability')
    op.drop_index(op.f('ix_product_availability_id'), table_name='product_availability')
    op.drop_index(op.f('ix_product_availability_delivery_window_id'), table_name='product_availability')
    op.drop_index(op.f('ix_product_availability_available_until'), table_name='product_availability')
    op.drop_index(op.f('ix_product_availability_available_from'), table_name='product_availability')
    op.drop_table('product_availability')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_session_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_route_stops_stop_status'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_order_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_seasonal'), table_name='products')
    op.drop_index(op.f('ix_products_producer_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_featured'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_active'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_producer_outreach_candidates_ubi'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_state'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_source_id'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_research_status'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_region'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_producer_name'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_producer_id'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_priority_score'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_priority_rank'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_outreach_status'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_import_run_id'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_id'), table_name='producer_outreach_candidates')
    op.drop_index(op.f('ix_producer_outreach_candidates_city'), table_name='producer_outreach_candidates')
    op.drop_table('producer_outreach_candidates')
    op.drop_index(op.f('ix_import_error_rows_import_run_id'), table_name='import_error_rows')
    op.drop_index(op.f('ix_import_error_rows_id'), table_name='import_error_rows')
    op.drop_table('import_error_rows')
    op.drop_index(op.f('ix_driver_payouts_route_id'), table_name='driver_payouts')
    op.drop_index(op.f('ix_driver_payouts_payout_status'), table_name='driver_payouts')
    op.drop_index(op.f('ix_driver_payouts_id'), table_name='driver_payouts')
    op.drop_index(op.f('ix_driver_payouts_driver_id'), table_name='driver_payouts')
    op.drop_table('driver_payouts')
    op.drop_index(op.f('ix_routes_route_status'), table_name='routes')
    op.drop_index(op.f('ix_routes_route_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_region'), table_name='routes')
    op.drop_index(op.f('ix_routes_reassignment_priority'), table_name='routes')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_driver_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_delivery_window_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_producers_website_url'), table_name='producers')
    op.drop_index(op.f('ix_producers_state'), table_name='producers')
    op.drop_index(op.f('ix_producers_source_listing_url'), table_name='producers')
    op.drop_index(op.f('ix_producers_source_id'), table_name='producers')
    op.drop_index(op.f('ix_producers_qualified'), table_name='producers')
    op.drop_index(op.f('ix_producers_producer_name'), table_name='producers')
    op.drop_index(op.f('ix_producers_online_order_url'), table_name='producers')
    op.drop_index(op.f('ix_producers_id'), table_name='producers')
    op.drop_index(op.f('ix_producers_city'), table_name='producers')
    op.drop_index(op.f('ix_producers_business_name'), table_name='producers')
    op.drop_table('producers')
    op.drop_index(op.f('ix_orders_stripe_payment_intent_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stripe_checkout_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_route_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivery_window_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_marketing_content_schedules_scheduled_date'), table_name='marketing_content_schedules')
    op.drop_index(op.f('ix_marketing_content_schedules_posting_status'), table_name='marketing_content_schedules')
    op.drop_index(op.f('ix_marketing_content_schedules_posting_platform'), table_name='marketing_content_schedules')
    op.drop_index(op.f('ix_marketing_content_schedules_marketing_content_id'), table_name='marketing_content_schedules')
    op.drop_index(op.f('ix_marketing_content_schedules_id'), table_name='marketing_content_schedules')
    op.drop_table('marketing_content_schedules')
    op.drop_index(op.f('ix_marketing_content_assets_marketing_content_id'), table_name='marketing_content_assets')
    op.drop_index(op.f('ix_marketing_content_assets_id'), table_name='marketing_content_assets')
    op.drop_index(op.f('ix_marketing_content_assets_asset_type'), table_name='marketing_content_assets')
    op.drop_table('marketing_content_assets')
    op.drop_index(op.f('ix_import_runs_source_id'), table_name='import_runs')
    op.drop_index(op.f('ix_import_runs_id'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_cart_sessions_status'), table_name='cart_sessions')
    op.drop_index(op.f('ix_cart_sessions_session_id'), table_name='cart_sessions')
    op.drop_index(op.f('ix_cart_sessions_id'), table_name='cart_sessions')
    op.drop_index(op.f('ix_cart_sessions_customer_id'), table_name='cart_sessions')
    op.drop_table('cart_sessions')
    op.drop_index(op.f('ix_waitlist_signups_state'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_source_page'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_signup_type'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_id'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_email'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_city'), table_name='waitlist_signups')
    op.drop_table('waitlist_signups')
    op.drop_index(op.f('ix_sources_state'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_region'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_active'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_producer_interests_state'), table_name='producer_interests')
    op.drop_index(op.f('ix_producer_interests_id'), table_name='producer_interests')
    op.drop_index(op.f('ix_producer_interests_email'), table_name='producer_interests')
    op.drop_index(op.f('ix_producer_interests_city'), table_name='producer_interests')
    op.drop_index(op.f('ix_producer_interests_business_name'), table_name='producer_interests')
    op.drop_table('producer_interests')
    op.drop_index(op.f('ix_marketing_content_title'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_target_platform'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_target_audience'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_status'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_scheduled_date'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_id'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_content_type'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_content_theme'), table_name='marketing_content')
    op.drop_index(op.f('ix_marketing_content_approved'), table_name='marketing_content')
    op.drop_table('marketing_content')
    op.drop_index(op.f('ix_drivers_territory'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_driver_interests_state'), table_name='driver_interests')
    op.drop_index(op.f('ix_driver_interests_id'), table_name='driver_interests')
    op.drop_index(op.f('ix_driver_interests_email'), table_name='driver_interests')
    op.drop_index(op.f('ix_driver_interests_city'), table_name='driver_interests')
    op.drop_table('driver_interests')
    op.drop_index(op.f('ix_delivery_windows_region'), table_name='delivery_windows')
    op.drop_index(op.f('ix_delivery_windows_name'), table_name='delivery_windows')
    op.drop_index(op.f('ix_delivery_windows_id'), table_name='delivery_windows')
    op.drop_index(op.f('ix_delivery_windows_delivery_date'), table_name='delivery_windows')
    op.drop_index(op.f('ix_delivery_windows_active'), table_name='delivery_windows')
    op.drop_table('delivery_windows')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
